blank_issues_enabled: false
contact_links:
  - name: General Issue
    url: https://github.com/official-Cromatin/ha-wilo/issues/new?template=general_issue.yml
    about: Nothing is matching your needs? Create an Normal issue